ALTER TABLE "citizen_requests"
ADD COLUMN "paymentMethod" TEXT NOT NULL DEFAULT 'REMOTE',
ADD COLUMN "paymentStatus" TEXT NOT NULL DEFAULT 'PENDING',
ADD COLUMN "withdrawalMethod" TEXT NOT NULL DEFAULT 'DOWNLOAD';
